### ISSUE TITLE
Upload to Leetify button is not showing

### ISSUE THREAD

**Issue by iS2Coke** [CSNADESgg/faceit-to-leetify-extension#4] opened 2024-07-19 22:18 UTC
![Capture](https://github.com/user-attachments/assets/9a4ec538-02c5-41aa-9189-fb1d76895eb1)

**Comment by retrolyze52** [comment] 2024-08-04 22:37
Same

**Comment by munger100** [comment] 2024-08-07 00:36
Hey, thanks for reaching out.

@iS2Coke Can you validate that this still happens, and let us know which browser you're using? 

@retrolyze52 Can you tell us what browser you're using, and additionally which language?

**Comment by retrolyze52** [comment] 2024-08-07 04:42
Chrome, English.

**Comment by munger100** [comment] 2024-08-07 23:04
@retrolyze52 I'm unable to reproduce the issue.

Please try removing and reinstalling the extension to see if that fixes it. 

If that doesn't fix it, please send me the link to the faceit lobby where it's not working, as well as the current version of your chrome browser, to help me reproduce your scenario as closely as possible.

**Comment by retrolyze52** [comment] 2024-08-08 16:16
@munger100 I've tried reinstalling the extension and the basic stuff that I could've tried and it still doesn't work.
I've seen reports of this happening in the Discord server from CSGONADES as well. 

I don't see the button on Leetify and I don't see the button on FACEIT.

Maybe the region is relevant? I've tried several extensions such as FACEIT enhancer (Now known as repeek) and it doesn't work too. I'm thinking this could be related to the region somehow. 

Region: South America (Includes Chile, Brazil, Argentina servers)
Language: English
Matchroom: https://www.faceit.com/en/cs2/room/1-7dd97b71-f34c-4cd8-bf90-c56c6075acc0

**Comment by retrolyze52** [comment] 2024-08-08 16:31
@munger100 I've tried reinstalling and basic stuff. I wouldn't be posting here otherwise.

With my mediocre knowledge I am starting to think that the reason for this could be the region. As you can see from the image @iS2Coke shared they're using Portuguese language, meaning they're playing in South America as well. I've tried several other extensions that improve FACEIT and most of them do not work either, example FACEIT Repeek. 

Region: South America (Brazil, Chile, Argentina servers)
Chrome: Version 127.0.6533.100 (Official Build) (64-bit)
Room: https://www.faceit.com/en/cs2/room/1-dfee1ab8-b9c3-4639-a6d4-0e657e245afe

It's not specific to any lobby, it doesn't work at all. 
The button does not show on FACEIT and it doesn't show on Leetify.

**Comment by Cretezy** [comment] 2024-08-09 19:52
![image](https://github.com/user-attachments/assets/2650f2be-bfbe-4e9b-b936-5dd7cbdb3007)

Are you sure you don't have any other FACEIT extensions installed? With a fresh Chrome profile I am able to see the button.

Our extension is _supposed_ to be language-agnostic, but could you also try with your FACEIT set to English?

Thank you!

**Comment by iS2Coke** [comment] 2024-08-09 21:28
It may be related to the Faceit beta version we have in SA [https://www.faceit.com/en/introduction/s-a-beta](url). 
![Faceit](https://github.com/user-attachments/assets/f2c81411-0420-4312-aadc-aebd90d66a2b). I've also tried to disable every other Faceit related extension.

**Comment by retrolyze52** [comment] 2024-08-10 20:06
@Cretezy As I said before I'm already using English. I think the problem is that we have BETA on our region and it doesn't work because of that. Is there a fix for this?

**Comment by Cretezy** [comment] 2024-08-10 21:10
Got it. It used to work with the beta, but something must've changed. I will take a look shortly if I still have the ability to test this.

**Comment by Cretezy** [comment] 2024-08-11 05:22
@retrolyze52 @iS2Coke Do you know how to activate the FACEIT beta? How would I know if I'm using the beta? Is it at beta.faceit.com?

(I can't seem to figure out how to activate it)

**Comment by retrolyze52** [comment] 2024-08-11 19:53
I've tried searching for an option related to BETA but I cannot find anything related to it. 
The page is the same "https://www.faceit.com/".  I don't think there's a way to activate / disable it.

**Closed** 2024-08-13 15:59 UTC
